config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'billing#index', as: :billing

  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success
  post '/subscription' => 'billing#subscribe', as: :subscribe
  get  '/show' => 'billing#show', as: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user.email
  end

  def new_card
    respond_to do |format|
      format.js
    end
  end

  def create_card
    # card_token = params[:stripeToken]
    # StripeService.create_card(current_user,card_token)
    respond_to do |format|
      if current_user.stripe_id.nil?
        customer = Stripe::Customer.create({"email": current_user.email})
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
        current_user.update(:stripe_id => customer.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end

      card_token = params[:stripeToken]
      #it's the stripeToken that we added in the hidden input
      if card_token.nil?
        format.html { redirect_to billing_path, error: "Oops"}
      end
      #checking if a card was giving.

      customer = Stripe::Customer.new current_user.stripe_id
      customer.source = card_token
      #we're attaching the card to the stripe customer
      customer.save

      format.html { redirect_to success_path }
    end
  end

  def success
    # @plans = Stripe::Plan.list.data
    @plans = Stripe::Product.retrieve('prod_JSOd8N2C9UZa76')
    @monthly = Stripe::Price.retrieve('price_1IpTqaCGGVUmh6uglk7nbNdl')
    # @yearly =  Stripe::Price.retrieve('price_1IoRIYKxvDwHPCEhyQ2TPvLS',)
  end

  def subscribe
    if current_user.stripe_id.nil?
      redirect_to success_path, :flash => {:error => 'Firstly you need to enter your card'}
      return
    end
    #if there is no card

    customer = Stripe::Customer.new current_user.stripe_id
    #we define our customer

    subscriptions = Stripe::Subscription.list(customer: customer.id)
    subscriptions.each do |subscription|
      subscription.delete
    end
    #we delete all subscription that the customer has. We do this because we don't want that our customer to have multiple subscriptions

    plan_id = params[:plan_id]
    subscription = Stripe::Subscription.create({
                                                 customer: customer,
                                                 items: [{plan: plan_id}], })
    #we are creating a new subscription with the plan_id we took from our form

    subscription.save
    redirect_to show_path
  end

  def show
    @user = current_user.email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/views/billing/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h1> Welcome  <%= @user %></h1>
    </div>
  </div>
  <div class="row">
    <h1 class="col-md-12 mt-5 text-center">
      Are you ready to pay?
    </h1>
  </div>
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <%= form_tag create_payment_method_path, id: "billing-create-payment-method" do  %>
        <%= link_to "Let's go", add_payment_method_path, remote: true, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/billing/new_card.js.erb
var handler = StripeCheckout.configure({
    key: '<%= Rails.application.credentials.stripe[Rails.env.to_sym][:publishable_key] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('billing-create-payment-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/billing/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h1> Thanks <%= @user %></h1>
    </div>
  </div>
  <div class="row">
    <h1 class="col-md-12 mt-5 text-center">
      You are subscribed now!
    </h1>
  </div>

</div>

app/views/billing/success.html.erb
<div class="row">
  <div class="col-md-12 mt-3 text-center">
    <h3>Now you need to choose your plan</h3>
  </div>
</div>
<!-- creating a form -->
<%=form_tag subscribe_path, method: :post do %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-center">
      <div class="form-group">
<!--        <select class="form-control" name="plan_id">-->
          <%# @plans.each do |plan| %>
<!--            <option value="<%#= plan.id %>"><%#= plan.amount/100 %>/€ <%#= plan.nickname %></option>-->
<!--            we pass id chosen by custmer as a value  to use it for subscription -->
          <%#end%>
<!--        </select>-->
        <select class="form-control" name="plan_id">
            <option value="<%= @monthly.id %>"><%= @monthly.unit_amount/100 %>/€ </option>
<!--          <option value="<%#= @yearly.id %>"><%#= @yearly.unit_amount/100 %>/€ </option>-->
        </select>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="col-md-12 mt-2 text-center">
      <%= submit_tag 'Save changes', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripePayment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>